// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
/*import { env } from './.env';*/

export const environment = {
  production: true,
  hmr: false,
  version: '0.0.1',
  serverUrl: 'http://192.168.52.92:3004/',
  defaultLanguage: 'fa-IR',
  supportedLanguages: ['fa-IR', 'en-US'],
  oath: {
    grantType: 'authorization_code',
    redirectUri: 'http://localhost:8080/los',
    clientId: 'los-ui-client',
    accessTokenUri: 'http://185.135.30.10:9443/identity/oauth2/auth/token',
    authorizationUri: 'http://185.135.30.10:9443/identity/oauth2/auth/authorize',
    clientSecret: 'bK4cF1cJ5lF6nH7kG6iI5mN5gL1vB3dP1jF4jC1qB1',
    scope: 'svc-mgmt-indv-lgl-foreign-cust-info',
  },
};
