spring:
  banner:
    location: classpath:bannername.txt
  application:
    name: los
  security:
    oauth2:
      client:
        registration:
          bmi-client:
            client-id: los-ui-client
            client-secret: bK4cF1cJ5lF6nH7kG6iI5mN5gL1vB3dP1jF4jC1qB1
            client-name: los-ui-client
            scope: svc-mgmt-indv-lgl-foreign-cust-info
            provider: bmi-provider
            redirect-uri: http://localhost:8080/los
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          bmi-provider:
            token-uri: http://185.135.30.10:9443/identity/oauth2/auth/token
            authorization-uri: http://185.135.30.10:9443/identity/oauth2/auth/authorize
